pipeline {
    agent any

    environment {
        APP_NAME = "kubeforge-app"
        AWS_REGION = "ap-south-1"

        // Safety switch (default OFF)
        DEPLOY_ENABLED = "false"

        K8S_NAMESPACE = "default"
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Set Build Metadata') {
            steps {
                script {
                    GIT_COMMIT_SHORT = sh(
                        script: "git rev-parse --short HEAD",
                        returnStdout: true
                    ).trim()

                    IMAGE_TAG = GIT_COMMIT_SHORT
                    IMAGE_NAME = "${APP_NAME}:${IMAGE_TAG}"

                    echo "Image to build: ${IMAGE_NAME}"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                  docker build -t ${IMAGE_NAME} ./app
                '''
            }
        }

        stage('CI Validation') {
            steps {
                sh '''
                  echo "Running basic validation"
                  echo "CI checks passed"
                '''
            }
        }

        stage('Deploy Green Version') {
            when {
                expression { env.DEPLOY_ENABLED == "true" }
            }
            steps {
                sh '''
                  echo "Deploying GREEN version"
                  kubectl apply -f kubernetes/base/deployment-green.yaml
                '''
            }
        }

        stage('Verify Green Deployment') {
            when {
                expression { env.DEPLOY_ENABLED == "true" }
            }
            steps {
                sh '''
                  echo "Waiting for GREEN pods to be ready"
                  kubectl rollout status deployment/kubeforge-green \
                    --namespace ${K8S_NAMESPACE}
                '''
            }
        }

        stage('Switch Traffic to Green') {
            when {
                expression { env.DEPLOY_ENABLED == "true" }
            }
            steps {
                sh '''
                  echo "Switching traffic to GREEN"
                  kubectl patch service kubeforge-service \
                    -p '{"spec":{"selector":{"app":"kubeforge","version":"green"}}}'
                '''
            }
        }
    }

    post {
        success {
            echo "Pipeline completed successfully"
        }
        failure {
            echo "Pipeline failed — traffic remains on BLUE"
        }
    }
}
